Vagrant.configure(2) do |config|
  config.vm.box_check_update = false
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "parallels" do |prl|
    prl.customize ["set", :id, "--startup-view", "headless"]
    prl.customize ["set", :id, "--videosize", "256"]
  end
end
